# basic information
# will be used to generate SEO and web content
title: Stranding Air
email: strandingair@outlook.com
description: ""

# Build settings
# custom defined collections
collections:
  - works
  - members
  - news

# sass partials location
sass:
    sass_dir: _sass

# define mobile
on_mobile: 600px

# plugins
plugins:
  - jekyll-seo-tag        # is used to generated seo tag